### ISSUE TITLE
Filter out NA responses 

### ISSUE THREAD

**Issue by jlbeaudry** [jlbeaudry/SOSTF_2019#20]
Tom, I was thinking about our decision to automatically filter out the NA responses within the function. Rather than making it automatic, can we include it as a parameter where we can make it TRUE or FALSE to make that decision? That will give us flexibility in how we deal with the data (for example, we wanted to include the NA responses for the Academic Level analysis so we could see how many chose not to tell us their position. 

Code within the function: 'the_data <- the_data[ !is.na(the_data[[label_var]]),]'

This isn't an immediate issue because I'm using the kable function for that variable, but this might be useful for other variables at some point.

**Comment by TomEmotion** [comment]
Yes, that sounds sensible and easily doable. Will get onto it

**Comment by jlbeaudry** [comment]
It works brilliantly! I added a note in the code re: which values it accepts, but otherwise all good. :)

**Comment by TomEmotion** [comment]
Excellent! Glad to know!
